-- MySQL Script generated by MySQL Workbench
-- Fri May 10 13:59:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NHTCU
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NHTCU
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NHTCU` DEFAULT CHARACTER SET utf8 ;
USE `NHTCU` ;

-- -----------------------------------------------------
-- Table `NHTCU`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NHTCU`.`Company` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UUIDCompany` VARCHAR(36) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `LandCode` VARCHAR(3) NOT NULL,
  `ChamberOfCommerce` VARCHAR(50) NOT NULL,
  `Owner` VARCHAR(50) NULL,
  `CEO` VARCHAR(50) NULL,
  `FoundedIn` DATE NULL,
  `EmployeeAmount` VARCHAR(50) NULL,
  `Size` VARCHAR(6) NULL,
  `CompanySector` VARCHAR(50) NULL,
  PRIMARY KEY (`ID`, `UUIDCompany`),
  UNIQUE INDEX `UIDCompany_UNIQUE` (`UUIDCompany` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NHTCU`.`Finance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NHTCU`.`Finance` (
  `UUIDFinance` VARCHAR(36) NOT NULL,
  `AccountNumber` VARCHAR(50) NULL,
  `Bank` VARCHAR(50) NULL,
  `VAT` VARCHAR(25) NULL,
  `Debt` DOUBLE NULL,
  `DebDate` DATE NULL,
  `SocialInsuranceTaxes` DOUBLE NULL,
  `SocialInsuranceTaxesDate` DATE NULL,
  `SocialSecurityInsurerCodes` VARCHAR(100) NULL,
  `Company_ID` INT NOT NULL,
  `Company_UUIDCompany` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`UUIDFinance`, `Company_ID`, `Company_UUIDCompany`),
  UNIQUE INDEX `UIDFinance_UNIQUE` (`UUIDFinance` ASC),
  INDEX `fk_Finance_Company1_idx` (`Company_ID` ASC, `Company_UUIDCompany` ASC),
  CONSTRAINT `fk_Finance_Company1`
    FOREIGN KEY (`Company_ID` , `Company_UUIDCompany`)
    REFERENCES `NHTCU`.`Company` (`ID` , `UUIDCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NHTCU`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NHTCU`.`Address` (
  `UUIDAddress` VARCHAR(36) NOT NULL,
  `Country` VARCHAR(50) NOT NULL,
  `State/Province` VARCHAR(50) NULL,
  `City` VARCHAR(50) NULL,
  `Street` VARCHAR(100) NULL,
  `StreetNumber` VARCHAR(10) NULL,
  `ZIP/PostalCode` VARCHAR(10) NULL,
  `Currency` VARCHAR(3) NULL,
  `Company_ID` INT NOT NULL,
  `Company_UUIDCompany` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`UUIDAddress`, `Company_ID`, `Company_UUIDCompany`),
  UNIQUE INDEX `UIDAddress_UNIQUE` (`UUIDAddress` ASC),
  INDEX `fk_Address_Company1_idx` (`Company_ID` ASC, `Company_UUIDCompany` ASC),
  CONSTRAINT `fk_Address_Company1`
    FOREIGN KEY (`Company_ID` , `Company_UUIDCompany`)
    REFERENCES `NHTCU`.`Company` (`ID` , `UUIDCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NHTCU`.`Domain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NHTCU`.`Domain` (
  `Domain` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Domain`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NHTCU`.`Internet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NHTCU`.`Internet` (
  `IPAddress` INT NOT NULL,
  `RecordMaintainedBy` VARCHAR(50) NULL,
  `DNS` VARCHAR(50) NULL,
  `Company_UUIDCompany` VARCHAR(36) NOT NULL,
  `Domain_Domain` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IPAddress`, `Company_UUIDCompany`, `Domain_Domain`),
  UNIQUE INDEX `IPAddress_UNIQUE` (`IPAddress` ASC),
  INDEX `fk_Internet_Company1_idx` (`Company_UUIDCompany` ASC),
  INDEX `fk_Internet_Domain1_idx` (`Domain_Domain` ASC),
  CONSTRAINT `fk_Internet_Company1`
    FOREIGN KEY (`Company_UUIDCompany`)
    REFERENCES `NHTCU`.`Company` (`UUIDCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Internet_Domain1`
    FOREIGN KEY (`Domain_Domain`)
    REFERENCES `NHTCU`.`Domain` (`Domain`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NHTCU`.`Scrape`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NHTCU`.`Scrape` (
  `DateOfScrape` DATETIME NOT NULL,
  `Source` VARCHAR(500) NOT NULL,
  `Company_ID` INT NOT NULL,
  `Company_UUIDCompany` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`DateOfScrape`, `Company_ID`, `Company_UUIDCompany`),
  UNIQUE INDEX `DateOfScrape_UNIQUE` (`DateOfScrape` ASC),
  INDEX `fk_Scrape_Company1_idx` (`Company_ID` ASC, `Company_UUIDCompany` ASC),
  CONSTRAINT `fk_Scrape_Company1`
    FOREIGN KEY (`Company_ID` , `Company_UUIDCompany`)
    REFERENCES `NHTCU`.`Company` (`ID` , `UUIDCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NHTCU`.`SubDomain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NHTCU`.`SubDomain` (
  `SubDomain` VARCHAR(50) NOT NULL,
  `Domain_Domain` VARCHAR(50) NOT NULL,
  `Internet_IPAddress` INT NOT NULL,
  `Internet_Company_UUIDCompany` VARCHAR(36) NOT NULL,
  `Internet_Domain_Domain` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`SubDomain`, `Domain_Domain`, `Internet_IPAddress`, `Internet_Company_UUIDCompany`, `Internet_Domain_Domain`),
  INDEX `fk_SubDomain_Domain1_idx` (`Domain_Domain` ASC),
  INDEX `fk_SubDomain_Internet1_idx` (`Internet_IPAddress` ASC, `Internet_Company_UUIDCompany` ASC, `Internet_Domain_Domain` ASC),
  CONSTRAINT `fk_SubDomain_Domain1`
    FOREIGN KEY (`Domain_Domain`)
    REFERENCES `NHTCU`.`Domain` (`Domain`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SubDomain_Internet1`
    FOREIGN KEY (`Internet_IPAddress` , `Internet_Company_UUIDCompany` , `Internet_Domain_Domain`)
    REFERENCES `NHTCU`.`Internet` (`IPAddress` , `Company_UUIDCompany` , `Domain_Domain`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NHTCU`.`Phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NHTCU`.`Phone` (
  `PhoneNumber` VARCHAR(50) NOT NULL,
  `Address_UUIDAddress` VARCHAR(36) NOT NULL,
  `Address_Company_ID` INT NOT NULL,
  `Address_Company_UUIDCompany` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`PhoneNumber`, `Address_UUIDAddress`, `Address_Company_ID`, `Address_Company_UUIDCompany`),
  INDEX `fk_Phone_Address1_idx` (`Address_UUIDAddress` ASC, `Address_Company_ID` ASC, `Address_Company_UUIDCompany` ASC),
  CONSTRAINT `fk_Phone_Address1`
    FOREIGN KEY (`Address_UUIDAddress` , `Address_Company_ID` , `Address_Company_UUIDCompany`)
    REFERENCES `NHTCU`.`Address` (`UUIDAddress` , `Company_ID` , `Company_UUIDCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NHTCU`.`Fax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NHTCU`.`Fax` (
  `FaxNumber` VARCHAR(50) NOT NULL,
  `Address_UUIDAddress` VARCHAR(36) NOT NULL,
  `Address_Company_ID` INT NOT NULL,
  `Address_Company_UUIDCompany` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`FaxNumber`, `Address_UUIDAddress`, `Address_Company_ID`, `Address_Company_UUIDCompany`),
  INDEX `fk_Fax_Address1_idx` (`Address_UUIDAddress` ASC, `Address_Company_ID` ASC, `Address_Company_UUIDCompany` ASC),
  CONSTRAINT `fk_Fax_Address1`
    FOREIGN KEY (`Address_UUIDAddress` , `Address_Company_ID` , `Address_Company_UUIDCompany`)
    REFERENCES `NHTCU`.`Address` (`UUIDAddress` , `Company_ID` , `Company_UUIDCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NHTCU`.`Email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NHTCU`.`Email` (
  `EmailAddress` VARCHAR(254) NOT NULL,
  `Company_ID` INT NOT NULL,
  `Company_UUIDCompany` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`EmailAddress`, `Company_ID`, `Company_UUIDCompany`),
  INDEX `fk_Email_Company1_idx` (`Company_ID` ASC, `Company_UUIDCompany` ASC),
  CONSTRAINT `fk_Email_Company1`
    FOREIGN KEY (`Company_ID` , `Company_UUIDCompany`)
    REFERENCES `NHTCU`.`Company` (`ID` , `UUIDCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;