-- MySQL Script generated by MySQL Workbench
-- Fri May 10 13:59:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema osintdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema osintdb
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS osintdb DEFAULT CHARACTER SET utf8 ;
USE osintdb;

-- -----------------------------------------------------
-- Table osintdb.Company
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS osintdb.Company (
  UUIDCompany VARCHAR(36) NOT NULL,
  Name VARCHAR(300) NOT NULL,
  LandCode VARCHAR(3) NOT NULL,
  ChamberOfCommerce VARCHAR(50) NOT NULL,
  Status VARCHAR(50) NULL,
  Owner VARCHAR(50) NULL,
  CEO VARCHAR(50) NULL,
  FoundedIn DATE NULL,
  EmployeeAmount VARCHAR(50) NULL,
  Size VARCHAR(25) NULL,
  CompanySector VARCHAR(50) NULL,
  PRIMARY KEY (UUIDCompany),
  UNIQUE INDEX UIDCompany_UNIQUE (UUIDCompany ASC)
    );


-- -----------------------------------------------------
-- Table osintdb.Finance
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS osintdb.Finance (
  UUIDFinance VARCHAR(36) NOT NULL,
  AccountNumber VARCHAR(50) NULL,
  Bank VARCHAR(50) NULL,
  VAT VARCHAR(50) NULL,
  Debt DOUBLE NULL,
  DebDate DATE NULL,
  SocialInsuranceTaxes DOUBLE NULL,
  SocialInsuranceTaxesDate DATE NULL,
  SocialSecurityInsurerCodes VARCHAR(150) NULL,
  Company_UUIDCompany VARCHAR(36) NOT NULL,
  PRIMARY KEY (UUIDFinance, Company_UUIDCompany),
  UNIQUE INDEX UIDFinance_UNIQUE (UUIDFinance ASC),
  INDEX fk_Finance_Company1_idx (Company_UUIDCompany ASC),
  CONSTRAINT fk_Finance_Company1
    FOREIGN KEY (Company_UUIDCompany)
    REFERENCES osintdb.Company (UUIDCompany)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table osintdb.Address
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS osintdb.Address (
  UUIDAddress VARCHAR(36) NOT NULL,
  Country VARCHAR(90) NOT NULL,
  Province VARCHAR(50) NULL,
  City VARCHAR(190) NULL,
  Street VARCHAR(100) NULL,
  StreetNumber VARCHAR(15) NULL,
  PostalCode VARCHAR(25) NULL,
  Currency VARCHAR(3) NULL,
  Company_UUIDCompany VARCHAR(36) NOT NULL,
  PRIMARY KEY (UUIDAddress, Company_UUIDCompany),
  UNIQUE INDEX UIDAddress_UNIQUE (UUIDAddress ASC),
  INDEX fk_Address_Company1_idx (Company_UUIDCompany ASC),
  CONSTRAINT fk_Address_Company1
    FOREIGN KEY (Company_UUIDCompany)
    REFERENCES osintdb.Company (UUIDCompany)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table osintdb.Domain
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS osintdb.Domain (
  Domain VARCHAR(50) NOT NULL,
  PRIMARY KEY (Domain));


-- -----------------------------------------------------
-- Table osintdb.Internet
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS osintdb.Internet (
  IPAddress INT NOT NULL,
  RecordMaintainedBy VARCHAR(50) NULL,
  DNS VARCHAR(50) NULL,
  Company_UUIDCompany VARCHAR(36) NOT NULL,
  Domain_Domain VARCHAR(50) NOT NULL,
  PRIMARY KEY (IPAddress, Company_UUIDCompany, Domain_Domain),
  UNIQUE INDEX IPAddress_UNIQUE (IPAddress ASC),
  INDEX fk_Internet_Company1_idx (Company_UUIDCompany ASC),
  INDEX fk_Internet_Domain1_idx (Domain_Domain ASC),
  CONSTRAINT fk_Internet_Company1
    FOREIGN KEY (Company_UUIDCompany)
    REFERENCES osintdb.Company (UUIDCompany)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Internet_Domain1
    FOREIGN KEY (Domain_Domain)
    REFERENCES osintdb.Domain (Domain)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table osintdb.Scrape
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS osintdb.Scrape (
  DateOfScrape DATETIME NOT NULL,
  Source VARCHAR(500) NOT NULL,
  Company_UUIDCompany VARCHAR(36) NOT NULL,
  PRIMARY KEY (DateOfScrape, Company_UUIDCompany),
  UNIQUE INDEX DateOfScrape_UNIQUE (DateOfScrape ASC),
  INDEX fk_Scrape_Company1_idx (Company_UUIDCompany ASC),
  CONSTRAINT fk_Scrape_Company1
    FOREIGN KEY (Company_UUIDCompany)
    REFERENCES osintdb.Company (UUIDCompany)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table osintdb.SubDomain
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS osintdb.SubDomain (
  SubDomain VARCHAR(50) NOT NULL,
  Domain_Domain VARCHAR(50) NOT NULL,
  Internet_IPAddress INT NOT NULL,
  Internet_Company_UUIDCompany VARCHAR(36) NOT NULL,
  Internet_Domain_Domain VARCHAR(50) NOT NULL,
  PRIMARY KEY (SubDomain, Domain_Domain, Internet_IPAddress, Internet_Company_UUIDCompany, Internet_Domain_Domain),
  INDEX fk_SubDomain_Domain1_idx (Domain_Domain ASC),
  INDEX fk_SubDomain_Internet1_idx (Internet_IPAddress ASC, Internet_Company_UUIDCompany ASC, Internet_Domain_Domain ASC),
  CONSTRAINT fk_SubDomain_Domain1
    FOREIGN KEY (Domain_Domain)
    REFERENCES osintdb.Domain (Domain)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_SubDomain_Internet1
    FOREIGN KEY (Internet_IPAddress , Internet_Company_UUIDCompany , Internet_Domain_Domain)
    REFERENCES osintdb.Internet (IPAddress , Company_UUIDCompany , Domain_Domain)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table osintdb.Phone
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS osintdb.Phone (
  PhoneNumber VARCHAR(50) NOT NULL,
  Address_UUIDAddress VARCHAR(36) NOT NULL,
  Address_Company_UUIDCompany VARCHAR(36) NOT NULL,
  PRIMARY KEY (PhoneNumber, Address_UUIDAddress, Address_Company_UUIDCompany),
  INDEX fk_Phone_Address1_idx (Address_UUIDAddress ASC, Address_Company_UUIDCompany ASC),
  CONSTRAINT fk_Phone_Address1
    FOREIGN KEY (Address_UUIDAddress , Address_Company_UUIDCompany)
    REFERENCES osintdb.Address (UUIDAddress , Company_UUIDCompany)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table osintdb.Fax
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS osintdb.Fax (
  FaxNumber VARCHAR(50) NOT NULL,
  Address_UUIDAddress VARCHAR(36) NOT NULL,
  Address_Company_UUIDCompany VARCHAR(36) NOT NULL,
  PRIMARY KEY (FaxNumber, Address_UUIDAddress, Address_Company_UUIDCompany),
  INDEX fk_Fax_Address1_idx (Address_UUIDAddress ASC, Address_Company_UUIDCompany ASC),
  CONSTRAINT fk_Fax_Address1
    FOREIGN KEY (Address_UUIDAddress , Address_Company_UUIDCompany)
    REFERENCES osintdb.Address (UUIDAddress , Company_UUIDCompany)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table osintdb.Email
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS osintdb.Email (
  EmailAddress VARCHAR(254) NOT NULL,
  Company_UUIDCompany VARCHAR(36) NOT NULL,
  PRIMARY KEY (EmailAddress, Company_UUIDCompany),
  INDEX fk_Email_Company1_idx (Company_UUIDCompany ASC),
  CONSTRAINT fk_Email_Company1
    FOREIGN KEY (Company_UUIDCompany)
    REFERENCES osintdb.Company (UUIDCompany)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
